### ISSUE TITLE
How can we switch between inEar and External speaker?

### ISSUE THREAD

**Issue by sthapa1** [aws-samples/amazon-chime-react-native-demo#125]
When I run the react native demo app, I can only access inear speaker but I can't switch to loudspeaker mode. How can we achieve that?

**Comment by alnlau** [comment]
Hello,

You can use `chooseAudioDevice` and `listAudioDevices` to do this ([Android](https://github.com/aws/amazon-chime-sdk-android/blob/master/amazon-chime-sdk/src/main/java/com/amazonaws/services/chime/sdk/meetings/device/DeviceController.kt#L27) [iOS](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDK/AmazonChimeSDK/device/DeviceController.swift#L19)). You will also have to update the bridge so that you can call these from React Native ([Android](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/android/app/src/main/java/com/amazonaws/services/chime/rndemo/NativeMobileSDKBridge.kt) [iOS](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/ios/RNDemo/NativeMobileSDKBridge.m)). Let us know if you have further questions

**Comment by sthapa1** [comment]
@alnlau I am new to Native android and IOS. Can you please send me just the steps to follow like in [https://github.com/aws-samples/amazon-chime-react-native-demo/issues/122#issue-1096035760](https://github.com/aws-samples/amazon-chime-react-native-demo/issues/122#issue-1096035760). That will help a lot. 
Thanks

**Comment by hokyungh** [comment]
Hi @sthapa1 could you take a look at https://github.com/aws-samples/amazon-chime-react-native-demo/pull/93?
