### ISSUE TITLE
RNVideoView overlay don't work

### ISSUE THREAD

**Issue by speedmetal** [aws-samples/amazon-chime-react-native-demo#23]
I have kept the call for 2 users only, where the other user's video would be full screen, and self video would be in a small box displayed over the full video. The videos are rendered using a RNVideoView component which is implemented natively by AWS Chime SDK, The problem is, when the small/self video view is rendered first it appears on top of the full video view, which is the correct behavior. But when it is being rendered after full/other user's video view it hides behind the full view, so the user himself would not be able to see his video stream

**Expected behavior**
The small video preview (self video) remains always over the big video (remote video)

**Additional context**
See here for more details:
https://stackoverflow.com/questions/63700333/small-video-view-hides-behind-full-video-in-video-call-react-native-aws-chime-s

**Comment by speedmetal** [comment]
Nobody care?

**Comment by tianyux-amz** [comment]
Hi @speedmetal,

Sorry for the late reply. I will try to reproduce the issue and get back to you later.

Best,
Tianyu

**Comment by tianyux-amz** [comment]
Hi @speedmetal,

I was able to reproduce the video overlapping issue, but with opposite reproduce steps: in my test, the video comes **later** will be on the top of the video came **before**. So if I enable local video first and then enable remote video, the remote (big) video will cover the local (small) video (instead of the other way around, as you mentioned in the issue).

The root cause of the issue is, we use SurfaceView to implement DefaultVideoRenderView, and we need to call [setZOrderMediaOverlay()](https://developer.android.com/reference/android/view/SurfaceView.html#setZOrderMediaOverlay(boolean)) to set the z-index order of SurfaceViews.

I was able to fix the issue by implementing a customized React Native property `isOnTop` in [RNVideoViewManager.kt](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/android/app/src/main/java/com/amazonaws/services/chime/rndemo/RNVideoViewManager.kt):
```
@ReactProp(name = "isOnTop")
fun setIsOnTop(renderView: DefaultVideoRenderView, isOnTop: Boolean) {
    renderView.setZOrderMediaOverlay(isOnTop)
}
```
Then in your RN code, you can check whether the video is a local video by checking `tileId === 0`, and set `isOnTop` accordingly:
```
<RNVideoRenderView
    style={tileId === 0 ? styles.selfVideo : styles.remoteVideo}
    key={tileId}
    tileId={tileId}
    isOnTop={tileId === 0}
/>
```

Please give it a try and let me know if it works. Thank you!

Best,
Tianyu

**Comment by speedmetal** [comment]
Thank you @tianyux-amz ! 
I think your solution solve the problem on Android, what i've to do for iOS device?

I'll give it a try, but i think the issue is not yet closed.

**Comment by tianyux-amz** [comment]
Hi @speedmetal ,

I tested the RN demo in iOS and I did not observe this issue. z-index works as expected.

Let me know if you run into similar issues in iOS. Thanks!

Best,
Tianyu

**Comment by aryapkurniawan15** [comment]
Hi @tianyux-amz, i developed similar app using java and in my case your solution cannot fix the problem, could you give me some suggestion on other ways i could fix this issue? Thank you.

**Comment by tianyux-amz** [comment]
Hi @aryapkurniawan15, the solution should work for both Java and Kotlin. Could you provide more details on what you have tried? It would be even better if you can share a minimal app that can reproduce the issue in Java. Thanks!

**Comment by tianyux-amz** [comment]
Saw @aryapkurniawan15 created an issue in https://github.com/aws/amazon-chime-sdk-android/issues/183. Will resolve this one and track the issue there.

**Comment by knvsshetty** [comment]
How to separate the user & opposite user RNVideoView Styles in amazon-chime-react-native.I tried using

this.state={selfVideoEnabled:false,videoTiles:[]

}
{this.state.videoTiles.length > 0 ? (
this.state.videoTiles.map((tileId) => (
<>
//for self user
{ tileId == 0 && this.state.selfVideoEnabled &&

}
//for opposite user
{ tileId == 2 &&

 <RNVideoRenderView
     key={tileId}
     tileId={tileId}
/>}
</>
)))
:
(
)}

i console tileid array also it giving initially [0,2] then after switching the video button multiple times its giving array as [0,2,2,2,2,2,0] etc. Can u please update on this issue
