### ISSUE TITLE
how to present active speaker on full screen to all attendees. 

### ISSUE THREAD

**Issue by rnqayush** [aws-samples/amazon-chime-react-native-demo#92]
1- I have implemented the active speaker code in my react native app and getting the response.

![activeS1](https://user-images.githubusercontent.com/74084740/124255526-e10fc480-db47-11eb-9908-7d64e26013ea.png)

2- I want to put the active speaker on fullscreen so as to make it visible to all the attendees joining. how i should achieve it?

**Comment by sagarpatel288** [comment]
@rnqayush 

1. Make sure that you are observing video tiles via `audioVideo?.addVideoTileObserver(context)`.
2. In order to present an active speaker on full screen, the active speaker will be required to start their local video first.
3. When they start their video, you should have it via video tile observer `VideoTileObserver` callback `onVideoTileAdded`. Watch out for other relevant video callbacks too.
4. From video tile state in `onVideoTileAdded`, you get an `attendeeId`. Store it. 
5. Now, in the active speaker list, you will get `attendeeId` via `attendeeInfo`. 
6. Find the `attendeeId` you get from the active speaker list and highlight (focus, UI change etc...) the video tile that has the same `attendeeId`.

**Comment by rnqayush** [comment]
1- @sagarpatel288  Actually I have followed the step and I am getting **attendeeId**  from **onVideoTileAdded** also i am getting active speaker.
2- I am doing log.i() and can see the active speaker logging on console
3- @sagarpatel288 @ajorg-aws @zhinang-amazon  how can i get that value from native  to my react native side. 



![activeS1](https://user-images.githubusercontent.com/74084740/124503369-0cfaa680-dde3-11eb-8371-896773e9d173.png)


![active ](https://user-images.githubusercontent.com/74084740/124502949-1b948e00-dde2-11eb-9467-2ddba9cc8586.png)

**Comment by sagarpatel288** [comment]
@rnqayush You can use [Callback](https://reactnative.dev/docs/native-modules-android#callbacks), or [Promises](https://reactnative.dev/docs/native-modules-android#promises), or [Events](https://reactnative.dev/docs/native-modules-android#sending-events-to-javascript).

**Comment by rnqayush** [comment]
thanks @sagarpatel288 i used event emitter and got it on my react native side too.

**Comment by rnqayush** [comment]
@sagarpatel288 thank you for your help I have done all steps and active speaker is now getting presented to fullscreen to all attendees.
